"use client";

// utils/mailer.ts
import { BookingInput } from "@/schemas/booking-schema";
import nodemailer from "nodemailer";

export const sendBookingEmail = async (booking: BookingInput) => {
  const transporter = nodemailer.createTransport({
    host: process.env.NEXT_SMTP_HOST,
    port: Number(process.env.NEXT_SMTP_PORT),
    auth: {
      user: process.env.NEXT_SMTP_USER,
      pass: process.env.NEXT_SMTP_PASS,
    },
  });

  const htmlContent = `
<div style="
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
  background-color: #f9fafb;
  padding: 40px;
  color: #111827;
">
  <div style="
    max-width: 560px;
    margin: 0 auto;
    background: #ffffff;
    border-radius: 12px;
    padding: 32px;
    border: 1px solid #e5e7eb;
  ">

    <!-- LOGO -->
    <div style="text-align: center; margin-bottom: 24px;">
      <img 
        src="https://exclusivo-five.vercel.app/exclusivo-logo.png" 
        alt="Exclusivo Logo" 
        style="width: 70px; height: auto; margin-bottom: 12px;"
      />
      <div style="
        font-size: 22px;
        font-weight: 700;
        letter-spacing: -0.5px;
        color: #111827;
      ">
        Exclusivo Barber Shop
      </div>
      <p style="margin-top: 4px; font-size: 14px; color: #6b7280;">
        Premium Grooming • Signature Cuts • Modern Style
      </p>
    </div>

    <!-- TITLE -->
    <h2 style="
      font-size: 20px;
      font-weight: 600;
      margin-bottom: 24px;
      color: #111827;
    ">
      New Booking Received
    </h2>

    <p style="font-size: 15px; color: #4b5563; margin-bottom: 24px;">
      A customer has submitted a booking request through your website.
      Here are the full details:
    </p>

    <!-- TABLE -->
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
      <tr>
        <td style="padding: 8px 0; font-weight: 600;">Name:</td>
        <td style="padding: 8px 0; color: #374151;">${booking.name}</td>
      </tr>
      <tr>
        <td style="padding: 8px 0; font-weight: 600;">Phone:</td>
        <td style="padding: 8px 0; color: #374151;">${booking.phone}</td>
      </tr>
      <tr>
        <td style="padding: 8px 0; font-weight: 600;">Date:</td>
        <td style="padding: 8px 0; color: #374151;">${booking.date}</td>
      </tr>
      <tr>
        <td style="padding: 8px 0; font-weight: 600;">Time:</td>
        <td style="padding: 8px 0; color: #374151;">${booking.selectedTime}</td>
      </tr>
      <tr>
        <td style="padding: 8px 0; font-weight: 600;">Barber:</td>
        <td style="padding: 8px 0; color: #374151;">${
          booking.selectedBarber
        }</td>
      </tr>
      <tr>
        <td style="padding: 8px 0; font-weight: 600;">Services:</td>
        <td style="padding: 8px 0; color: #374151;">${booking.selectedServices.join(
          ", "
        )}</td>
      </tr>
      <tr>
        <td style="padding: 8px 0; font-weight: 600;">Note:</td>
        <td style="padding: 8px 0; color: #374151;">${
          booking.note || "No note."
        }</td>
      </tr>
    </table>

    <!-- FOOTER -->
    <p style="
      font-size: 12px;
      color: #9ca3af;
      margin-top: 32px;
      text-align: center;
      line-height: 1.6;
    ">
      This message was automatically generated by the Exclusivo Website.<br>
      If you did not expect this email, you may safely ignore it.
    </p>

  </div>
</div>
`;

  const mailOptions = {
    from: `"Barber Booking" <${process.env.NEXT_SMTP_USER}>`,
    to: process.env.NEXT_BOOKING_RECEIVER,
    subject: `New Booking from ${booking.name}`,
    html: htmlContent,
  };

  await transporter.sendMail(mailOptions);
};
